version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: aeros-postgis
    environment:
      POSTGRES_USER: aeros
      POSTGRES_PASSWORD: aeros_password
      POSTGRES_DB: aeros_db
    ports:
      - "5432:5432"
    volumes:
      - aeros_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  aeros_pgdata:
